### ISSUE TITLE
Can't switch account on pushbullet

### ISSUE THREAD

**Issue by burtgulash** [jariz/tabbie#49]
Once I sign in with my fb account I can't switch over to my google account.

**Comment by jariz** [comment]
This is more a problem for Pushbullet than Tabbie. They should give you a logout button on the approval page.  
Because redddit does have this:  
![](http://i.imgur.com/qJc7x47.png)  
Which allows you to switch between accounts when logged in.  
  
I can however, provide you with a workaround:  
- Open the login dialog by clicking the 'sign in' button.
- Type `chrome://inspect` into the addressbar.  
- Go to apps in the left menu.
- Beneath PushBullet, click 'Inspect'  
- In the window that now opens, hit ESC  
- Paste the following: `localStorage.clear();window.location=""`  
  
I can't really do anything about it, You might wanna contact PushBullet to request this.

**Comment by burtgulash** [comment]
Thanks for the workaround! Works perfectly
