### ISSUE TITLE
Zoom effect on mouse hover is really annoying. 

### ISSUE THREAD

**Issue by brendengreenwood** [jariz/tabbie#65]
Hey, thanks for putting so much time and work into this great application. It's become such a big part of my day with out my even realizing until now. I love being able to see at a glance what's going on in my worlds. 

First off, let me preface this by saying that I am a UX/UI designer so I think about this kind of stuff all. So, just just prepare yourself for some feedback, lol. 

Despite how much I enjoy the app, I really think you should kill the zooming hover effect. It looks kind of cool at first but it is such a jarring motion in an of itself, and when it fires everytime you move your mouse accros a column that has it...me no like. Plus, there isn't a real purpose to have it there to begin with. It doesn't communicate something other than you've hovered and you've already got another hover animation happening as well. I think It actually takes away from those details that are showing on top of of the image. It's sort of just design fluff/noise. I think it would make for a better experience if there was no hover. 

Also, concerning those details desplayed on hover. It might work better to use a card layout for each inividual item with all that info already in view. Could be kind of weird with your column layout, but, doing so would actually be more in line with the Material spec. Just a thought. 

Thanks again!

**Comment by jariz** [comment]
I will probably remove the zoom effect, but the cards idea.. I love cards,
but there's just not enough space for that. That's the whole reason no
cards are used in any columns at all right now.
Tabbie still has to look decent on low resolutions (on a 13" retina macbook
for example), and with 4 columns next to each other, you end up with very
little space.

I like the dribbble/behance columns because they show a lot of content,
even when there's not that much space available. I want to to scroll as
least as possible, and in the end, those columns are all about the images.

If you have any more ideas/criticism/anything to add on what I said, keep
it coming, because I'm not a UX, nor a UI designer. (Or any designer at all
really)
