### ISSUE TITLE
Auto-hide scrollbars

### ISSUE THREAD

**Issue by runofthemill** [jariz/tabbie#66]
Hey jariz - been working on some tweaks to tabbie and amongst other things, auto-hid scroll bars. I think it helps keep the screen a little more clutter-free; if you like it, I can put that feature in it's own branch and do a PR. It's here right now: https://github.com/runofthemill/tabbie/tree/producthunt-update

(sorry if this isn't the right way to go about this - somewhat of a github contributing novice :P )

**Comment by jariz** [comment]
Hey Jeremy, That'd be great to have.
Everyone needs to start somewhere, let me give you some advice:
It is probably best if you made a separate branch (and pull request) for each feature (the scrolling, and the product hunt edits)? I wanted to look at your PR (#73) but it also contains the scroll stuff and a whole lot of other stuff (and unnecessary commits) which makes it a bit chaotic. So yea, in the future, don't update it later if you're going outside the scope of your pull request because if you make changes, they'll also get added to your pull request.

To easily create a new commit with changes you already made check out [git cherry-pick](http://git-scm.com/docs/git-cherry-pick) (if you use a UI, check if the UI supports cherry picking)

**Comment by jariz** [comment]
Also, pull changes regularly! Your current branch is pretty out of sync.

**Comment by runofthemill** [comment]
makes sense! just learned the magic of git reset --hard upstream/master :+1:
