### ISSUE TITLE
Adding websites with Feedly causes their thumbnails to appear at the bottom of the screen

### ISSUE THREAD

**Issue by californicator** [jariz/tabbie#73]
![image](https://cloud.githubusercontent.com/assets/7904551/7986375/964b91e6-0ad7-11e5-8b09-3704e37222ed.png)
After I've added some websites with Feedly, their tiles have appeared on the bottom of the page.

**Comment by californicator** [comment]
Update: the issue disappears after opening the browser again.

**Comment by californicator** [comment]
Update 2: never mind, they reappeared after a while.

**Comment by jariz** [comment]
This happens when tabbie fails to detect the color of an image because it has no permission to the image.
Tabbie however, asks for permissions to these images when you click the '+' button for the first time on the 'add column' page, so this shouldn't even be possible.  
Have you attempted reinstalling Tabbie already? (removing it from chrome, then installing again)
If that doesn't solve it, can you hit ctrl+shift+j and screenshot it after the tiles show up?

**Comment by californicator** [comment]
Reinstalled it, gave it the permissions, nothing changed.

![zrzut ekranu 1257](https://cloud.githubusercontent.com/assets/7904551/7990229/e21363c0-0aef-11e5-9b70-dd80841a985d.png)

Here's the full content of Chrome's console window in case the important thing isn't on the screen (didn't want to send multiple screenshots).
http://pastebin.com/xjpTc9bA

**Comment by jariz** [comment]
Haven't seen this anywhere else, ever again, so closing for the moment.
